### ISSUE TITLE
New windows when downloading without compression

### ISSUE THREAD

**Issue by PanuWeb** [Kharg/download-all-attachments#1]
Hello! Cool extension.

When I select the "single" download mode, a new window/tab opens for each file to be downloaded.

Although this works, it results in after the tabs are closed, the focus doesn't return to the last tab I was positioned on. Also visually it looks a bit strange that tabs are opened and closed so quickly.

I wanted to propose that instead of opening windows: create links and simulate a click with JS, and then delete it.

This is how I do it in one of my projects:

```js
const link = document.createElement( 'a' );

link.style.display = 'none';

document.body.appendChild( link );

for ( let i = 0; i < urls.length; i++ ) {
	filename = ''; // <<< GET THE NAME OF THE FILE TO DOWNLOAD
	link.setAttribute( 'href', urls[ i ] );
	link.setAttribute( 'download', filename );
	link.click();
}

document.body.removeChild( link );
```
This code is not tested in all browsers, I have only used it in Chrome but it works.

The first time, the user has to accept the multiple download, but it is the same as accepting new windows to open.

In this way the download process is more "clean" for the user.

I'm pretty rusty in programming for Espo to encourage me to do a Pull Request of the code, so I leave it here.

I hope it works.

Greetings!

**Comment by Kharg** [comment]
Hi,

if you could do a pull request I can try to adapt the code to work with Espo in the best possible way or find alternative solutions to the problem.

At first I wanted to develop an alternative entrypoint that could do that, but it looks like there's no way to develop this feature in PHP.

If you can't pull request I will try to adapt my own solution

**Comment by PanuWeb** [comment]
I can't provide a pull request as that would take a lot of time for me. I am testing and giving contributions, since you were lucky today is a holiday in my country and I have free time.

Anyway I can add this to my previous answer this:

File to edit: `/files/client/modules/download-all-attachments/src/extensions/views/fields/attachment-multiple.js`
Function: `downloadAllAttachments` (line 23)
[Link to the líne](https://github.com/Kharg/download-all-attachments/blob/9e1d8a693ba2be9d67b0d511fd2bea5709660121/files/client/modules/download-all-attachments/src/extensions/views/fields/attachment-multiple.js#L23)

Instead of using `window.open(url, '_blank');` or `window.open(separateUrl, '_blank');` you would use the code I gave you to create a link, simulate the click, and then remove the link .

I don't think it's necessary to edit the PHP with that change in JS would be enough.

In any case, it's a proposal for improvement, so it's already working and it can stay that way.

Greetings!

**Comment by Kharg** [comment]
Added in version 1.0.1
