### ISSUE TITLE
Possibility to add two buttons: download as ZIP or Simple

### ISSUE THREAD

**Issue by PanuWeb** [Kharg/download-all-attachments#2]
Hello!

Can you add the possibility of having two buttons to be able to choose whether to download the files as ZIP or individually?

I leave an example

![image](https://user-images.githubusercontent.com/110789/230613455-6f7aa41f-a4dc-4a7f-8ffd-6473467bdc4e.png)
![image](https://user-images.githubusercontent.com/110789/230614364-cbebf221-df64-43b4-bec4-adfd44ce9782.png)

This allows you to choose the download form according to each email.

Thank you!

**Comment by Kharg** [comment]
Hi,

This is a nice idea but I think that it would require a major rewrite of the logic.

I will work on this for the next update! :)

**Comment by Kharg** [comment]
Added in 1.1.0

**Comment by PanuWeb** [comment]
Tested! it works perfectly

**Comment by Kharg** [comment]
@PanuWeb did you get an update notification in your admin panel for the new version?

**Comment by PanuWeb** [comment]
No no. I didn't know there was that functionality. I just downloaded the ZIP from github and re-uploaded it
