### ISSUE TITLE
The button is not shown when there are only images

### ISSUE THREAD

**Issue by PanuWeb** [Kharg/download-all-attachments#3]
Hello!

I found a problem. When the email only has attached images, the download all button does not appear.

I leave capture

![image](https://user-images.githubusercontent.com/110789/233780397-23b87d2f-6abc-4dac-9657-17d6fdb1827b.png)
(yes, the client completed the PDF and sends it to me as images 😂)

I don't know what could be due

Saludos!

**Comment by Kharg** [comment]
Hi,
thanks for reporting.
Do you get any error in the browser console?

**Comment by PanuWeb** [comment]
Nop, the console is empty

![image](https://user-images.githubusercontent.com/110789/233781234-858ff9e1-e8a4-4100-ae32-e78079ca5853.png)

The only thing I can see is that the links (images) are in a different `<div>` block, and are listed as attachment preview

![image](https://user-images.githubusercontent.com/110789/233781338-204552e8-5e6a-4a02-aed7-24f9fe0b49b1.png)

![image](https://user-images.githubusercontent.com/110789/233781360-f18b93af-9e54-4eea-99e0-e6928a2d6c1e.png)

**Comment by Kharg** [comment]
Ohh, then that's why.
I will update the extension as soon as possible :)

**Comment by Kharg** [comment]
Fixed with version 1.1.1

Let me know if it works correctly!

**Comment by PanuWeb** [comment]
It works but the buttons were added in the last image instead of adding below

![image](https://user-images.githubusercontent.com/110789/233796816-d649c713-7cb0-46bd-81fa-432ac8d289dc.png)

**Comment by Kharg** [comment]
This could be solved by making the extension create a new div probably, but I am afraid it would look too ugly or cause many more issues.

**Comment by PanuWeb** [comment]
In that case, no problem. I prefer functionality over aesthetics. Thank you!
